#!/usr/bin/env python3
from datetime import datetime, timezone
VERSION='CLASS_210_COUNTEREXAMPLE_CAUSAL_FAMILY_V1'
CASES=[
 {'parcel_id':'0905012000300007000','property_address':'64 POTUNK LN','family':'EXCEPTIONAL_IMPROVEMENT_SCALE','assessment_route_survives':False,'facts':{'class':'210','acres':1.53,'living_sqft':8300,'beds':9,'baths':'8_FULL_2_HALF','land_assessment':670200.0,'total_assessment':4184900.0,'improvement_assessment':3514700.0,'historic_core_year':1924,'recent_renovation_context':2018,'amenities':['POOL','SPA','MULTIPLE_FIREPLACES','DETACHED_GARAGE']},'meaning':'Large amenity-heavy estate improvement scale explains persistently high improvement-to-land relationship; statistical extremeness alone is not an opportunity signal.','next_research_need':'NO_FURTHER_ASSESSMENT_CAUSE_RESEARCH; PRESERVE INDEPENDENT PROPERTY/LAND/OWNERSHIP ROUTES'},
 {'parcel_id':'0905015000300002001','property_address':'66A BEACH LN','family':'EXCEPTIONAL_IMPROVEMENT_SCALE','assessment_route_survives':False,'facts':{'class':'210','acres':0.919,'living_sqft':5782,'beds':6,'baths':8,'land_assessment':724000.0,'improvement_assessment':2140300.0,'pool':True,'improvement_history':'LONG_STABLE'},'meaning':'Large estate-scale residence and amenities materially explain the persistent high improvement component; no recent redevelopment discontinuity is required.','next_research_need':'NO_FURTHER_ASSESSMENT_CAUSE_RESEARCH; PRESERVE INDEPENDENT PROPERTY/LAND/OWNERSHIP ROUTES'},
 {'parcel_id':'0905014000100009000','property_address':'21 SEAFIELD LN','family':'EXCEPTIONAL_IMPROVEMENT_SCALE','assessment_route_survives':False,'facts':{'class':'210','acres':1.02,'living_sqft':6941,'beds':7,'baths':7,'land_assessment':900600.0,'improvement_assessment':2286300.0,'historic_core_year':1930,'expanded':1994,'pool':True,'improvement_history':'LONG_STABLE'},'meaning':'Large estate-scale residence, legacy expansion and amenities materially explain the persistent improvement-heavy assessment profile.','next_research_need':'NO_FURTHER_ASSESSMENT_CAUSE_RESEARCH; PRESERVE INDEPENDENT PROPERTY/LAND/OWNERSHIP ROUTES'},
 {'parcel_id':'0905011000300031000','property_address':'58 LIBRARY AVE','family':'PROPERTY_FORM_MISMATCH','assessment_route_survives':False,'facts':{'source_class':'210','parcel_level_sqft':6008,'authoritative_context':'SUFFOLK_COOP_INVENTORY_IDENTIFIES_HARBOR_VIEW_AT_58_LIBRARY_AVE_AS_13_UNIT_COOPERATIVE','conversion_context':'MOTEL_CONVERSION_1980','unit_level_context':'STOCK_COOPERATIVE_UNITS'},'meaning':'Parcel-level class-210 comparison is semantically misleading because the address represents a cooperative property form; ordinary single-family physical-peer interpretation is invalid.','next_research_need':'ROUTE PROPERTY THROUGH PROPERTY_FORM SEMANTICS BEFORE ANY FUTURE PEER COMPARISON'},
 {'parcel_id':'0905008000100024000','property_address':'104 ONECK LN','family':'UNRESOLVED_STAGED_CHANGE_SOURCE_CONFLICT','assessment_route_survives':True,'facts':{'class':'210','acres':0.27,'living_sqft':1596,'beds':3,'public_year_built_conflict':[2015,2019],'assessment_history':'STAGED_CHANGE','2025_land':257700.0,'2025_improvement':577050.0},'meaning':'Neither redevelopment discontinuity, exceptional estate scale, nor property-form mismatch currently explains the assessment route. Conflicting construction-year evidence and staged assessment changes remain material.','next_research_need':'ONE_AUTHORITATIVE_BUILDING/PERMIT_OR_ASSESSOR_HISTORY_FACT TO RESOLVE CURRENT STRUCTURE TIMELINE; DO NOT INFER CAUSALITY'}
]
def build_class_210_counterexample_causal_family_v1():
    kills=sum(not c['assessment_route_survives'] for c in CASES)
    return {'status':'ok','version':VERSION,'mode':'READ_ONLY_COUNTEREXAMPLE_CAUSAL_FAMILY_RESOLUTION','generated_at':datetime.now(timezone.utc).isoformat(),'cases':CASES,'summary':{'counterexamples_received':5,'assessment_route_kills_supported':kills,'assessment_routes_preserved':5-kills,'exceptional_improvement_scale':3,'property_form_mismatch':1,'unresolved_staged_change_source_conflict':1,'endpoint_external_calls':0},'reusable_patterns':{'EXCEPTIONAL_IMPROVEMENT_SCALE':{'effect':'KILL_ASSESSMENT_ANOMALY_ROUTE_ONLY','required_evidence':['LARGE_OR_COMPLEX_IMPROVEMENT_SCALE','CORROBORATED_PHYSICAL_OR_AMENITY_INTENSITY','ASSESSMENT_COMPONENT_CONSISTENT_WITH_IMPROVEMENT_SCALE'],'not_sufficient_alone':['HIGH_PRICE','LARGE_HOUSE','HIGH_ASSESSMENT']},'PROPERTY_FORM_MISMATCH':{'effect':'INVALIDATE_ORDINARY_SINGLE_FAMILY_PEER_INTERPRETATION','required_evidence':['AUTHORITATIVE_OR_STRONG_CORROBORATED_NONSTANDARD_PROPERTY_FORM','PEER_METHOD_ASSUMES_ORDINARY_SINGLE_FAMILY_FORM']}},'decision':{'bulk_external_lookup_authorized':False,'resolved_assessment_routes_stop_here':True,'104_oneck_remains_alive':True,'independent_routes_always_preserved':True},'next_if_verified':'MERGE CLASS_210 CAUSAL FAMILIES; TARGET 104 ONECK WITH ONE AUTHORITATIVE STRUCTURE-TIMELINE FACT; THEN CLOSE CLASS_210 ASSESSMENT-CAUSE BRANCH OR PRESERVE THE FINAL UNRESOLVED CASE','policy':{'kill_route_not_property':True,'causal_evidence_required':True,'property_form_semantics_precede_peer_interpretation':True,'missing_information_nonblocking':True,'seller_intent_inferred':False,'marketing_execution':False},'database_writes':0,'guards':{'database_writes':False,'external_calls':False,'schema_changes':False,'investigate_state_touched':False,'v19v_touched':False,'seller_qualification_changes':False,'seller_intent_inferred':False,'seller_scoring':False,'overall_ranking':False,'contact_authorized':False,'outreach_touched':False}}
